
#include "library.h"

struct fsex_category patch_category[] = {
	{ "---", "No assign" },
	{ "PNO", "Acoustic Piano" },
	{ "EP ", "Electric Piano" },
	{ "KEY", "Keyboards" },
	{ "BEL", "Bell" },
	{ "MLT", "Mallet" },
	{ "ORG", "Organ" },
	{ "ACD", "Accordion" },
	{ "HRM", "Harmonica" },
	{ "AGT", "Acoustic Guitar" },
	{ "EGT", "Electric Guitar" },
	{ "DGT", "Distorted Guitar" },
	{ "BS ", "Bass" },
	{ "SBS", "Synth Bass" },
	{ "STR", "Strings" },
	{ "ORC", "Orchestra" },
	{ "HIT", "Hit&Stab" },
	{ "WND", "Wind" },
	{ "FLT", "Flute" },
	{ "BRS", "Acoustic Brass" },
	{ "SBR", "Synth Brass" },
	{ "SAX", "Sax" },
	{ "HLD", "Hard Lead" },
	{ "SLD", "Soft Lead" },
	{ "TEK", "Techno Synth" },
	{ "PLS", "Pulsating" },
	{ "FX ", "Synth FX" },
	{ "SYN", "Other Synth" },
	{ "BPD", "Bright Pad" },
	{ "SPD", "Soft Pad" },
	{ "VOX", "Vox" },
	{ "PLK", "Plucked" },
	{ "ETH", "Ethnic" },
	{ "FRT", "Fretted" },
	{ "PRC", "Percussion" },
	{ "SFX", "Sound FX" },
	{ "BTS", "Beat&Groove" },
	{ "DRM", "Drums" },
	{ "CMB", "Combination" },
};

