.TH "FLIB" "1" "Version 0\&.1" "Jun 2007" "Fantom Utilities" 
.PP 
.SH "NAME" 
fsex - Fantom SysEx Utility
.PP 
.SH "SYNOPSIS" 
\fBfsex\fP
[options]
[action]
[input files]
[output file]
.PP 
.SH "DESCRIPTION" 
\fBflib\fP is a utility to manage data from the librarian program of Fantom\&,
Juno-G and other Roland synthesizers based on the XV engine\&. Currently
supported formats are .jgl, .fxl and .fsl.
.PP 
.SH "OPTIONS" 
The following options can be used when running flib:
.IP "\fB-f, --force\fP" 
Force overwrite of existing output files\&.
.IP "\fB-q, --quiet\fP" 
Don't print messages to stdout\&.
.PP
.SH "ACTION"
Exactly one of the following actions should be selected when running flib:
.IP "\fB-e, --extract\fP"
Extract the listed patches from the input files and write to the output
file\&. See section FILE FORMAT below for the file format specification\&.
.IP "\fB-l, --list\fP" 
List patches from the input files\&.
.IP "\fB-h, --help\fP" 
Show a short summary of command-line options\&.
.IP "\fB-V, --version\fP" 
Print version information\&.
.PP 
.SH "FILE FORMAT" 
The input files can be specified in a `filename:patch_list' format where
\fIpatch_list\fP is a comma-separated list of numeric ranges\&. An optional
`!' can be used at the beginning of \fIpatch_list\fP to invert the list\&.
If no patch list is specified, all patches in \fIfilename\fP are selected\&.
.PP
.SH "EXAMPLES" 
List patches in a Juno-G JGL file:
.IP "" 
\f(CWflib -l Sineshine.jgl\fP
.PP 
Create a new library called New.jgl containing patches 2, 4, 5 and 6
from Sineshine.jgl:
.IP "" 
\f(CWflib -e Sineshine.jgl:2,4-6 New.jgl\fP
.PP 
Create a new library called New.jgl containing the first patch from
Sineshine.jgl plus all patches in XV_Collection.jgl except the first one:
.IP "" 
\f(CWflib -e Sineshine.jgl:1 XV_Collection.jgl:!1 New.jgl\fP
.PP 
.SH "BUGS" 
Certainly we have some, but we don't know where they are\&. Please report
any bugs you find\&.
.PP 
.SH "AUTHOR" 
Written by Claudio Matsuoka <cmatsuoka@gmail.com>\&.
.PP 
.SH "SEE ALSO" 
fsex(1)\&, aconnect(1)\&, Roland MIDI implementation
.PP 
