.TH "FLIB" "1" "Version 0\&.1" "Jun 2007" "Fantom Utilities" 
.PP 
.SH "NAME" 
fsex - Fantom SysEx Utility
.PP 
.SH "SYNOPSIS" 
\fBfsex\fP
[\fB-d, --delete\fP \fIlist\fP]
[\fB-e, --extract\fP \fIlist\fP]
[\fB-l, --list\fP]
[\fB-h, --help\fP]
[\fB-o, --output\fP \fIname\fP]
[\fB-V, --version\fP]
.PP 
.SH "DESCRIPTION" 
\fBflib\fP is a utility to manage data from the librarian program of Fantom\&,
Juno-G and other Roland synthesizers based on the XV engine\&. Currently
supported formats are .jgl, .fxl and .fsl.
.PP 
.SH "OPTIONS" 
.IP "\fB-d, --delete\fP \fIlist\fP"
Delete the listed patches from the library and write a new library
file specified with the -o option\&. \fIlist\fP is a comma-separated list of
patch numbers and ranges\&. Example: 1,3-5,20-25\&.
.IP "\fB-e, --extract\fP \fIlist\fP"
Extract the listed patches from the library and write to a new library
file specified with the -o option\&. See parameter -d for information
on \fIlist\fP format.
.IP "\fB-l, --list\fP" 
List patches from librarian file.
reply\&.
.IP "\fB-h, --help\fP" 
Show a short summary of command-line options\&.
.IP "\fB-V, --version\fP" 
Print version information\&.
.IP "\fB-o, --output\fP \fIname\fP"
Set the output file name when using -d or -e.
.PP 
.SH "EXAMPLES" 
List patches in a Juno-G JGL file:
.IP "" 
\f(CWflib -l Sineshine.jgl\fP
.PP 
Create a new library called New.jgl containing patches 2, 4, 5 and 6
from Sineshine.jgl:
.IP "" 
\f(CWflib -e 2,4-6 -o New.jgl Sineshine.jgl\fP
.PP 
Create a new library called New.jgl containing all patches in
XV_Collection.jgl except the first one:
.IP "" 
\f(CWflib -d 1 -o New.jgl XV_Collection.jgl\fP
.PP 
.SH "BUGS" 
Certainly we have some, but we don't know where they are\&. Please report
any bugs you find\&.
.PP 
.SH "AUTHOR" 
Written by Claudio Matsuoka <cmatsuoka@gmail.com>\&.
.PP 
.SH "SEE ALSO" 
fsex(1)\&, aconnect(1)\&, Roland MIDI implementation
.PP 
