.TH "FLIB" "1" "Version 0\&.1" "Jun 2007" "Fantom Utilities" 
.PP 
.SH "NAME" 
fsex - Fantom SysEx Utility
.PP 
.SH "SYNOPSIS" 
\fBfsex\fP
[\fB-l, --list\fP]
[\fB-h, --help\fP]
[\fB-V, --version\fP]
.PP 
.SH "DESCRIPTION" 
\fBflib\fP is a utility to manage data from the librarian program of Fantom\&,
Juno-G and other Roland synthesizers based on the XV engine\&. Currently
supported formats are .jgl, .fxl and .fsl.
.PP 
.SH "OPTIONS" 
.IP "\fB-l, --list\fP" 
List patches from librarian file.
reply\&.
.IP "\fB-h, --help\fP" 
Show a short summary of command-line options\&.
.IP "\fB-V, --version\fP" 
Print version information\&.
.PP 
.SH "EXAMPLES" 
List patches in a Juno-G JGL file:
.IP "" 
\f(CWglib -l Sineshine.jgl\fP
.PP 
.SH "BUGS" 
Certainly we have some, but we don't know where they are yet\&.
.PP 
.SH "AUTHOR" 
Written by Claudio Matsuoka\&.
.PP 
.SH "SEE ALSO" 
fsex(1)\&, aconnect(1)\&, Roland MIDI implementation
.PP 
