
char *junog_wave[] = {
	"(unset)",
	"Juno Saw HD",
	"TB303 Saw HD",
	"Custm Saw HD",
	"Real MG Saw",
	"MG Saw HD",
	"700 Saw A",
	"700 Saw B",
	"700 Saw C",
	"OB2 Saw HD",
	"DigitalSawHD",
	"Calc.Saw",
	"Calc.Saw inv",
	"Synth Saw",
	"JD Syn Saw",
	"JD Fat Saw",
	"JP-8 Saw",
	"P5 Saw HD",
	"D-50 Saw",
	"Air Wave",
	"Unison Saw A",
	"Unison Saw B",
	"Unison Saw C",
	"Super Saw A",
	"Super Saw B",
	"Super Saw C",
	"Trance Saw A",
	"Trance Saw B",
	"Trance Saw C",
	"Alpha Rave",
	"Saw Sync A",
	"Saw Sync B",
	"Saw Sync C",
	"TB Dst Saw A",
	"TB Dst Saw B",
	"TB Dst Saw C",
	"Juno Sqr HD",
	"MG Sqr HD",
	"P5 Sqr HD",
	"OB2 Sqr HD",
	"Custm Sqr HD",
	"106SubOsc HD",
	"TB303 Sqr HD",
	"Fat Square",
	"JP-8 Square",
	"TB DstSqr 1A",
	"TB DstSqr 1B",
	"TB DstSqr 1C",
	"Dist SquareA",
	"Dist SquareB",
	"Dist SquareC",
	"Juno Pls HD",
	"JP8 Pls 05HD",
	"JP8 Pls 15HD",
	"JP8 Pls 25HD",
	"JP8 Pls 30HD",
	"JP8 Pls 40HD",
	"JP8 Pls 45HD",
	"Syn Pulse 1",
	"Syn Pulse 2",
	"MG Tri HD",
	"700 Triangle",
	"Syn Triangle",
	"JD Triangle",
	"ARP Sine HD",
	"Sine",
	"CalcSIN2",
	"KG800 Lead",
	"MG Fs Lead",
	"Juno Saw+Sub",
	"260 Sub OSC",
	"Spct2 20",
	"JD EML 5th",
	"SBF Hrd Ld 1",
	"SBF Hrd Ld 2",
	"Digi Attack",
	"JD Fine Wine",
	"Digi Loop 1",
	"Digi Loop 2",
	"JD MetalWind",
	"Atmosphere",
	"DigiSpectrum",
	"JD Vox Noise",
	"SynVox Noise",
	"Shaku Noise",
	"Digi Breath",
	"Agogo Noise",
	"Polishing Nz",
	"Dentist Nz",
	"Vinyl Noise",
	"White Noise",
	"Pink Noise",
	"SBF Cym Lp",
	"SBF Bell Lp",
	"SBF Nz Lp",
	"MG Bass 1 A",
	"MG Bass 1 B",
	"MG Bass 1 C",
	"DistTB Sqr",
	"DistTBSqr Lp",
	"Solid Bass",
	"MG Big Bass",
	"Jungle Bass",
	"Garage Bass",
	"106 Bs56",
	"SH-101 Bs A",
	"SH-101 Bs B",
	"SH-101 Bs C",
	"TB Natural",
	"Poly Bass",
	"Organ Bass",
	"Voco Bass",
	"MG Bass 2 A",
	"MG Bass 2 B",
	"MG Bass 2 C",
	"MG Bass 3",
	"MG Bass 4",
	"MC Bass A",
	"MC Bass B",
	"MC Bass C",
	"SH-101 Bs 4A",
	"SH-101 Bs 4B",
	"SH-101 Bs 4C",
	"Atk Syn Bass",
	"Warm Pad A",
	"Warm Pad B",
	"Warm Pad C",
	"OB2 Pad 1 A",
	"OB2 Pad 1 B",
	"OB2 Pad 1 C",
	"OB2 Pad 2 A",
	"OB2 Pad 2 B",
	"OB2 Pad 2 C",
	"D-50 HeavenA",
	"D-50 HeavenB",
	"D-50 HeavenC",
	"Syn Vox 1 A",
	"Syn Vox 1 B",
	"Syn Vox 1 C",
	"Syn Vox 2 A",
	"Syn Vox 2 B",
	"Syn Vox 2 C",
	"SBF Vox A",
	"SBF Vox B",
	"SBF Vox C",
	"SBF Vox Lp",
	"Aah Formant",
	"Eeh Formant",
	"Iih Formant",
	"Ooh Formant",
	"Uuh Formant",
	"Ac.Pno p A L",
	"Ac.Pno p A R",
	"Ac.Pno p B L",
	"Ac.Pno p B R",
	"Ac.Pno p C L",
	"Ac.Pno p C R",
	"Ac.Pno f A L",
	"Ac.Pno f A R",
	"Ac.Pno f B L",
	"Ac.Pno f B R",
	"Ac.Pno f C L",
	"Ac.Pno f C R",
	"JD Piano A",
	"JD Piano B",
	"JD Piano C",
	"Piano Atk Nz",
	"MKS Piano A",
	"MKS Piano B",
	"MKS Piano C",
	"Stage EP p A",
	"Stage EP p B",
	"Stage EP p C",
	"Stage EP f A",
	"Stage EP f B",
	"Stage EP f C",
	"Tine EP p A",
	"Tine EP p B",
	"Tine EP p C",
	"Tine EP mf A",
	"Tine EP mf B",
	"Tine EP mf C",
	"Tine EP ff A",
	"Tine EP ff B",
	"Tine EP ff C",
	"Dyno EP mp A",
	"Dyno EP mp B",
	"Dyno EP mp C",
	"Dyno EP mf A",
	"Dyno EP mf B",
	"Dyno EP mf C",
	"Dyno EP ff A",
	"Dyno EP ff B",
	"Dyno EP ff C",
	"Wurly mp A",
	"Wurly mp B",
	"Wurly mp C",
	"Wurly mf A",
	"Wurly mf B",
	"Wurly mf C",
	"Wurly ff A",
	"Wurly ff B",
	"Wurly ff C",
	"Lo-Fi Wurly",
	"Soft SA EP A",
	"Soft SA EP B",
	"Soft SA EP C",
	"Hard SA EP A",
	"Hard SA EP B",
	"Hard SA EP C",
	"SA EP Ens A",
	"SA EP Ens B",
	"SA EP Ens C",
	"SA E.Piano A",
	"SA E.Piano B",
	"SA E.Piano C",
	"80?s E.Pno 1",
	"80?s E.Pno 2",
	"Hard E.Pno",
	"Celesta",
	"Music Box",
	"Reg.Clav A",
	"Reg.Clav B",
	"Reg.Clav C",
	"Retro Clav A",
	"Retro Clav B",
	"Retro Clav C",
	"Tight Clav A",
	"Tight Clav B",
	"Tight Clav C",
	"Hard Clav A",
	"Hard Clav B",
	"Hard Clav C",
	"JD Clav",
	"Harpsi A",
	"Harpsi B",
	"Harpsi C",
	"JD Full Draw",
	"Org Basic 1",
	"Org Basic 2",
	"Ballad Org",
	"3rd Perc Org",
	"Lo-Fi Organ",
	"Perc Organ 1",
	"Perc Organ 2",
	"Rock Organ A",
	"Rock Organ B",
	"Rock Organ C",
	"RtryOrg1 A L",
	"RtryOrg1 A R",
	"RtryOrg1 B L",
	"RtryOrg1 B R",
	"RtryOrg1 C L",
	"RtryOrg1 C R",
	"RtryOrg2 A L",
	"RtryOrg2 A R",
	"RtryOrg2 B L",
	"RtryOrg2 B R",
	"RtryOrg2 C L",
	"RtryOrg2 C R",
	"LoFi RtryOrg",
	"Vint.Org 1",
	"Vint.Org 2",
	"Vint.Org 3",
	"Vint.Org 4",
	"R_ORGAN A",
	"Lite Dst Org",
	"Positive ?8",
	"Pipe Organ",
	"Cathedrl Org",
	"Nylon Gtr1 A",
	"Nylon Gtr1 B",
	"Nylon Gtr1 C",
	"Nylon Gtr2 A",
	"Nylon Gtr2 B",
	"Nylon Gtr2 C",
	"Bright Gtr A",
	"Bright Gtr B",
	"Bright Gtr C",
	"Ac.Gtr mp A",
	"Ac.Gtr mp B",
	"Ac.Gtr mp C",
	"Ac.Gtr mf A",
	"Ac.Gtr mf B",
	"Ac.Gtr mf C",
	"Ac.Gtr ff A",
	"Ac.Gtr ff B",
	"Ac.Gtr ff C",
	"Ac.Gtr Sld A",
	"Ac.Gtr Sld B",
	"Ac.Gtr Sld C",
	"Ac.Gtr Hrm A",
	"Ac.Gtr Hrm B",
	"Ac.Gtr Hrm C",
	"Jazz Gtr A",
	"Jazz Gtr B",
	"Jazz Gtr C",
	"Clean Gtr A",
	"Clean Gtr B",
	"Clean Gtr C",
	"Clr Mt Gtr A",
	"Clr Mt Gtr B",
	"Clr Mt Gtr C",
	"E.Gtr Ld 1",
	"E.Gtr Ld 2",
	"Brt Strat A",
	"Brt Strat B",
	"Brt Strat C",
	"SlwPick70s A",
	"SlwPick70s B",
	"SlwPick70s C",
	"FstPick70s A",
	"FstPick70s B",
	"FstPick70s C",
	"Plk Strat A",
	"Plk Strat B",
	"Plk Strat C",
	"Strat Mute A",
	"Strat Mute B",
	"Strat Mute C",
	"Funk Gtr A",
	"Funk Gtr B",
	"Funk Gtr C",
	"Funk MtGtr A",
	"Funk MtGtr B",
	"Funk MtGtr C",
	"Easy Gtr A",
	"Easy Gtr B",
	"Easy Gtr C",
	"Nasty Gtr",
	"Clean TC A",
	"Clean TC B",
	"Clean TC C",
	"Overdrive A",
	"Overdrive C",
	"Distortion A",
	"Distortion B",
	"Distortion C",
	"Dist Mute A",
	"Dist Mute B",
	"Dist Mute C",
	"Dist Chord A",
	"Dist Chord B",
	"Dist Chord C",
	"Dst Gtr Riff",
	"Gtr Trill",
	"Cln Gtr Cut",
	"Gtr Cut 1",
	"Gtr Cut 2",
	"Gtr Cut 3",
	"Gtr Cut 4",
	"Wah Gtr Riff",
	"E.Gtr Harm",
	"JD ScrapeGut",
	"Harp A",
	"Harp B",
	"Harp C",
	"Banjo A",
	"Banjo B",
	"Banjo C",
	"Sitar A",
	"Sitar B",
	"Sitar C",
	"Sitar Drn A",
	"Sitar Drn B",
	"Sitar Drn C",
	"E.Sitar A",
	"E.Sitar B",
	"E.Sitar C",
	"Santur A",
	"Santur B",
	"Santur C",
	"Dulcimer A",
	"Dulcimer B",
	"Dulcimer C",
	"Shamisen A",
	"Shamisen B",
	"Shamisen C",
	"Koto A",
	"Koto B",
	"Koto C",
	"Ac.Bass A",
	"Ac.Bass B",
	"Ac.Bass C",
	"FngrCmp Bs A",
	"FngrCmp Bs B",
	"FngrCmp Bs C",
	"Finger Bs A",
	"Finger Bs B",
	"Finger Bs C",
	"Precision Bs",
	"Jz Bs Soft A",
	"Jz Bs Soft B",
	"Jz Bs Soft C",
	"6-FngBsSft A",
	"6-FngBsSft B",
	"6-FngBsSft C",
	"ThumbMtBs pA",
	"ThumbMtBs pB",
	"ThumbMtBs pC",
	"ThumbMtBs fA",
	"ThumbMtBs fB",
	"ThumbMtBs fC",
	"Fretlss Bs A",
	"Fretlss Bs B",
	"Fretlss Bs C",
	"Fretlss SftA",
	"Fretlss SftB",
	"Fretlss SftC",
	"Pick Bass 1A",
	"Pick Bass 1B",
	"Pick Bass 1C",
	"Pick Bass 2",
	"Slap Bass",
	"Slap +Pull 1",
	"Slap +Pull 2",
	"Slap +Pull 3",
	"Jz Slap Bass",
	"Jz Slp+Pull1",
	"Jz Slp+Pull2",
	"Jz Slp+Pull3",
	"Atk Flute A",
	"Atk Flute B",
	"Atk Flute C",
	"Flute A",
	"Flute B",
	"Flute C",
	"Piccolo A",
	"Piccolo B",
	"Piccolo C",
	"Pan Flute",
	"JD Rad Hose",
	"Shakuhachi",
	"JD Fl Push",
	"Clarinet A",
	"Clarinet B",
	"Clarinet C",
	"Oboe Mezzo A",
	"Oboe Mezzo B",
	"Oboe Mezzo C",
	"Oboe Forte A",
	"Oboe Forte B",
	"Oboe Forte C",
	"E.Horn A",
	"E.Horn B",
	"E.Horn C",
	"Bassoon A",
	"Bassoon B",
	"Bassoon C",
	"Recorder A",
	"Recorder B",
	"Recorder C",
	"SopranoSax A",
	"SopranoSax B",
	"SopranoSax C",
	"Alto Sax Vib",
	"Soft Alto A",
	"Soft Alto B",
	"Soft Alto C",
	"Wide Sax A",
	"Wide Sax B",
	"Wide Sax C",
	"BreathySax A",
	"BreathySax B",
	"BreathySax C",
	"Tenor Sax A",
	"Tenor Sax B",
	"Tenor Sax C",
	"Bari.Sax 1 A",
	"Bari.Sax 1 B",
	"Bari.Sax 1 C",
	"Bari.Sax 2 A",
	"Bari.Sax 2 B",
	"Bari.Sax 2 C",
	"Musette",
	"Harmonica A",
	"Harmonica B",
	"Harmonica C",
	"Blues G-harp",
	"Flugel A",
	"Flugel B",
	"Flugel C",
	"Trumpet A",
	"Trumpet B",
	"Trumpet C",
	"Wide Tp A",
	"Wide Tp B",
	"Wide Tp C",
	"Mute Tp A",
	"Mute Tp B",
	"Mute Tp C",
	"Trombone A",
	"Trombone B",
	"Trombone C",
	"Tbn mf A",
	"Tbn mf B",
	"Tbn mf C",
	"Tuba A",
	"Tuba B",
	"Tuba C",
	"Sft F.Horn A",
	"Sft F.Horn B",
	"Sft F.Horn C",
	"French Hrn A",
	"French Hrn C",
	"F.HornSect A",
	"F.HornSect B",
	"F.HornSect C",
	"Tp Section A",
	"Tp Section B",
	"Tp Section C",
	"OctBrs p A L",
	"OctBrs p A R",
	"OctBrs p B L",
	"OctBrs p B R",
	"OctBrs p C L",
	"OctBrs p C R",
	"OctBrs f A L",
	"OctBrs f A R",
	"OctBrs f B L",
	"OctBrs f B R",
	"OctBrs f C L",
	"OctBrs f C R",
	"Brs Fall 1 L",
	"Brs Fall 1 R",
	"Brs Fall 2 L",
	"Brs Fall 2 R",
	"OrchUnis A L",
	"OrchUnis A R",
	"OrchUnis B L",
	"OrchUnis B R",
	"OrchUnis C L",
	"OrchUnis C R",
	"Violin Vib A",
	"Violin Vib B",
	"Violin Vib C",
	"Violin A",
	"Violin B",
	"Violin C",
	"Cello Vib A",
	"Cello Vib B",
	"Cello Vib C",
	"Cello A",
	"Cello B",
	"Cello C",
	"Vl Sect. A L",
	"Vl Sect. A R",
	"Vl Sect. B L",
	"Vl Sect. B R",
	"Vl Sect. C L",
	"Vl Sect. C R",
	"Vc Sect. A L",
	"Vc Sect. A R",
	"Vc Sect. B L",
	"Vc Sect. B R",
	"Vc Sect. C L",
	"Vc Sect. C R",
	"Full Str A L",
	"Full Str A R",
	"Full Str B L",
	"Full Str B R",
	"Full Str C L",
	"Full Str C R",
	"ChmbrStrAtkA",
	"ChmbrStrAtkB",
	"ChmbrStrAtkC",
	"ChmbrStrRevA",
	"ChmbrStrRevB",
	"ChmbrStrRevC",
	"Vls Pizz A",
	"Vls Pizz B",
	"Vls Pizz C",
	"VlsPizzRev A",
	"VlsPizzRev B",
	"VlsPizzRev C",
	"Vcs Pizz A",
	"Vcs Pizz B",
	"Vcs Pizz C",
	"VcsPizzRev A",
	"VcsPizzRev B",
	"VcsPizzRev C",
	"PizzyTechno",
	"Female Ahs A",
	"Female Ahs B",
	"Female Ahs C",
	"Female Oos A",
	"Female Oos B",
	"Female Oos C",
	"Male Aahs A",
	"Male Aahs B",
	"Male Aahs C",
	"Jazz Doos A",
	"Jazz Doos B",
	"Jazz Doos C",
	"Jz Doos Lp A",
	"Jz Doos Lp B",
	"Jz Doos Lp C",
	"Gospel Hum A",
	"Gospel Hum B",
	"Gospel Hum C",
	"Soprano Vox",
	"Kalimba",
	"JD Klmba Atk",
	"JD Wood Crak",
	"JD Gamelan 1",
	"JD Gamelan 2",
	"JD Gamelan 3",
	"JD Log Drum",
	"JD Hooky",
	"JD Tabla",
	"JD Xylo",
	"Marimba",
	"Vibraphone",
	"Glocken",
	"Steel Drums",
	"JD Pole Lp",
	"JD BottleHit",
	"D-50 Bell A",
	"D-50 Bell B",
	"D-50 Bell C",
	"D-50 Bell Lp",
	"Agogo Bell",
	"Finger Bell",
	"JD Cowbell",
	"Tubular Bell",
	"Church Bell",
	"Mild CanWave",
	"JD Crystal",
	"Bell Organ",
	"Old DigiBell",
	"JD Bell Wave",
	"TinyBellWave",
	"Vib Wave",
	"JD Brt Digi",
	"Med Digi",
	"Bagpipe",
	"Digital Vox",
	"JD WallyWave",
	"JD Brusky Lp",
	"Bright Form",
	"Mild Form",
	"JD Nasty",
	"Fat SparkVox",
	"JD Spark Vox",
	"JD Cutters",
	"JD Rattles",
	"Xylo Seq.",
	"JD Tin Wave",
	"JD Anklungs",
	"JD Shami",
	"SynBassClick",
	"JD EP Atk",
	"EP Release",
	"Org Click 1",
	"Org Click 2",
	"Org Click 3",
	"Org Click 4",
	"Org Click 5",
	"Org Leakage",
	"MG Noise Fx",
	"JD Sm Metal",
	"JDStrikePole",
	"Ice Crash",
	"JD Switch",
	"JD Tuba Slap",
	"JD Plink",
	"JD Plunk",
	"TVF Trigger",
	"Cutting Nz",
	"Ac.Bass Body",
	"Flute Pad Nz",
	"Applause",
	"River",
	"Thunder",
	"Monsoon",
	"Stream",
	"Bubble",
	"Bird Song",
	"Dog Bark",
	"Gallop",
	"Vint.Phone",
	"Office Phone",
	"Mobile Phone",
	"Door Creak",
	"Door Slam",
	"Car Engine",
	"Car Slip",
	"Car Pass",
	"Crash Seq.",
	"Gun Shot",
	"Siren",
	"Train Pass",
	"Airplane",
	"Space Voyage",
	"Blow Loop",
	"Laugh",
	"Scream",
	"Punch",
	"Heartbeat",
	"Footsteps",
	"Machine Gun",
	"Laser",
	"Thunder Lp",
	"Ac.Bass Nz 1",
	"Ac.Bass Nz 2",
	"E.Bass Nz 1",
	"E.Bass Nz 2",
	"E.Bass Slide",
	"DistGtr Nz 1",
	"DistGtr Nz 2",
	"DistGtr Nz 3",
	"GtrStroke Nz",
	"Gtr Fret Nz1",
	"Gtr Fret Nz2",
	"Gtr Fret Nz3",
	"ClassicHseHt",
	"OrangeHit 1",
	"OrangeHit 2",
	"OrangeHit 3",
	"7th Hit",
	"Brassy Hit",
	"Drive Hit",
	"Filtered Hit",
	"Mild Hit",
	"Narrow Hit 1",
	"Narrow Hit 2",
	"Euro Hit",
	"Dist Hit",
	"Thin Beef",
	"Tao Hit",
	"Smear Hit 1",
	"Smear Hit 2",
	"LoFi Min Hit",
	"Orch. Hit",
	"Punch Hit",
	"O?Skool Hit",
	"Philly Hit",
	"Metal Vox W1",
	"Metal Vox L1",
	"Metal Vox W2",
	"Metal Vox L2",
	"Metal Vox W3",
	"Metal Vox L3",
	"Scratch 1",
	"Scratch 2",
	"Scratch 3",
	"Scratch 4",
	"Scratch 5",
	"Scratch 6",
	"Scratch 7",
	"Scratch 8",
	"Scratch 9",
	"Scratch 10",
	"MG Zap 1",
	"MG Zap 2",
	"MG Zap 3",
	"MG Zap 4",
	"MG Zap 5",
	"MG Zap 6",
	"MG Zap 7",
	"MG Zap 8",
	"MG Zap 9",
	"MG Zap 10",
	"MG Zap 11",
	"MG Blip",
	"Beam HiQ",
	"MG Attack",
	"Syn Low Atk1",
	"Syn Low Atk2",
	"Syn Hrd Atk1",
	"Syn Hrd Atk2",
	"Syn Hrd Atk3",
	"Syn Hrd Atk4",
	"Syn Mtl Atk1",
	"Syn Mtl Atk2",
	"Syn Swt Atk1",
	"Syn Swt Atk2",
	"Syn Swt Atk3",
	"Syn Swt Atk4",
	"Syn Swt Atk5",
	"Syn Swt Atk6",
	"Syn Swt Atk7",
	"Reg.Kick p L",
	"Reg.Kick p R",
	"Reg.Kick f L",
	"Reg.Kick f R",
	"Reg.Kick ffL",
	"Reg.Kick ffR",
	"Rock Kick p",
	"Rock Kick f",
	"Jazz Kick p",
	"Jazz Kick mf",
	"Jazz Kick f",
	"Dry Kick 1",
	"Tight Kick 1",
	"Tight Kick 2",
	"Old Kick",
	"Jz Dry Kick",
	"Bright Kick",
	"Dry Kick 2",
	"Dry Kick 3",
	"Power Kick",
	"R&B Kick L",
	"R&B Kick R",
	"Rk CmpKick L",
	"Rk CmpKick R",
	"MaxLow Kick1",
	"MaxLow Kick2",
	"MaxLow Kick3",
	"Dist Kick",
	"FB Kick",
	"Rough Kick1",
	"Rough Kick2",
	"Rough Kick3",
	"Click Kick",
	"Pick Kick",
	"Back Kick",
	"Vinyl Kick",
	"Low Kick 1",
	"Boys Kick",
	"Hippie Kick",
	"Frenzy Kick",
	"PlasticKick1",
	"Swallow Kick",
	"Neck Kick",
	"70?s Kick",
	"Skool Kick",
	"Dance Kick",
	"HipHop Kick1",
	"HipHop Kick2",
	"Pin Kick",
	"Low Kick 2",
	"Low Kick 3",
	"AnalogKick 1",
	"PlasticKick2",
	"PlasticKick3",
	"TR909 Kick 1",
	"TR909 Kick 2",
	"AnalogKick 2",
	"TR909 Kick 3",
	"AnalogKick 3",
	"AnalogKick 4",
	"AnalogKick 5",
	"AnalogKick 6",
	"TR606DstKick",
	"TR808 Kick",
	"TR909 Kick 4",
	"TR909 Kick 5",
	"SH32 Kick",
	"TR707 Kick",
	"TR909 Kick 6",
	"Roll Kick",
	"Reg.Snr1 p L",
	"Reg.Snr1 p R",
	"Reg.Snr1mf L",
	"Reg.Snr1mf R",
	"Reg.Snr1 f L",
	"Reg.Snr1 f R",
	"Reg.Snr1ff L",
	"Reg.Snr1ff R",
	"Reg.Snr2 p L",
	"Reg.Snr2 p R",
	"Reg.Snr2 f L",
	"Reg.Snr2 f R",
	"Reg.Snr2ff L",
	"Reg.Snr2ff R",
	"Reg.SnrFlm L",
	"Reg.SnrFlm R",
	"Amb.Snr1 p L",
	"Amb.Snr1 p R",
	"Amb.Snr1 f L",
	"Amb.Snr1 f R",
	"Amb.Snr2 p L",
	"Amb.Snr2 p R",
	"Amb.Snr2 f L",
	"Amb.Snr2 f R",
	"Piccolo Snr",
	"Maple Snr",
	"Natural Snr1",
	"Natural Snr2",
	"Dry Snr p",
	"Dry Snr f",
	"Ballad Snr",
	"Light Snr p",
	"Light Snr f",
	"Light Snr ff",
	"Light SnrRim",
	"Click Snr p",
	"Click Snr f",
	"Click Snr ff",
	"Rock Snr p",
	"Rock Snr mf",
	"Rock Snr f",
	"Rock Rim p",
	"Rock Rim mf",
	"Rock Rim f",
	"Reg.SnrGst L",
	"Reg.SnrGst R",
	"Rock Snr Gst",
	"Sft Snr Gst",
	"Jazz Snr p",
	"Jazz Snr mf",
	"Jazz Snr f",
	"Jazz Snr ff",
	"Jazz Rim p",
	"Jazz Rim mf",
	"Jazz Rim f",
	"Jazz Rim ff",
	"Jz Brsh Slap",
	"Jz Brsh Swsh",
	"Swish&Turn p",
	"Swish&Turn f",
	"Snr Roll",
	"Snr Roll Lp",
	"Soft Jz Roll",
	"BrushRoll Lp",
	"GoodOld Snr1",
	"GoodOld Snr2",
	"GoodOld Snr3",
	"GoodOld Snr4",
	"GoodOld Snr5",
	"GoodOld Snr6",
	"Dirty Snr 1",
	"Dirty Snr 2",
	"Dirty Snr 3",
	"Dirty Snr 4",
	"Dirty Snr 5",
	"Dirty Snr 6",
	"Dirty Snr 7",
	"Dirty Snr 8",
	"Dirty Snr 9",
	"Dirty Snr 10",
	"Grit Snr 1",
	"Grit Snr 2",
	"Grit Snr 3",
	"Grit Snr 4",
	"LoBit SnrFlm",
	"Lo-Bit Snr 1",
	"Lo-Bit Snr 2",
	"Lo-Bit Snr 3",
	"BmbCmp Snr",
	"MrchCmp Snr",
	"Frenzy Snr 1",
	"Frenzy Snr 2",
	"Slap Snr 1",
	"Keen Snr 1",
	"Reggae Snr",
	"DR660 Snr",
	"Pop Snr p",
	"Pop Snr f",
	"Pop Snr Rim",
	"Med Snare",
	"Jngl pkt Snr",
	"Pocket Snr",
	"Flange Snr",
	"Slap Snr 2",
	"Analog Snr 1",
	"Analog Snr 2",
	"Analog Snr 3",
	"Jam Snr",
	"Back Snr",
	"Keen Snr 2",
	"Boys Snr 1",
	"Slap Snr 3",
	"Neck Snr",
	"Artful Snr",
	"Pin Snr",
	"Chemical Snr",
	"Sizzle Snr",
	"Tiny Snare",
	"R&B Snare 1",
	"R&B Snare 2",
	"Cross Snr",
	"Grave Snr",
	"Boys Snr 2",
	"Boys Snr 3",
	"Low Down Snr",
	"TR909 Snr 1",
	"TR909 Snr 2",
	"TR909 Snr 3",
	"TR909 Snr 4",
	"TR909 Snr 5",
	"TR909 Snr 6",
	"TR808 Snr 1",
	"TR808 Snr 2",
	"TR808 Snr 3",
	"TR808 Snr 4",
	"Lite Snare",
	"TR808 Snr 5",
	"TR808 Snr 6",
	"TR808 Snr 7",
	"TR606 Snr 1",
	"TR606 Snr 2",
	"CR78 Snare",
	"Urbn Sn Roll",
	"Jngl SnrRoll",
	"Reg.Stick L",
	"Reg.Stick R",
	"Soft Stick",
	"Hard Stick",
	"Wild Stick",
	"Rock Stick",
	"Lo-Bit Stk 1",
	"Lo-Bit Stk 2",
	"Lo-Bit Stk 3",
	"Lo-Bit Stk 4",
	"Dry Stick 1",
	"Dry Stick 2",
	"Dry Stick 3",
	"Dry Stick 4",
	"Dry Stick 5",
	"R8 Comp Rim",
	"R&B Rim 1",
	"R&B Rim 2",
	"R&B Rim 3",
	"Neck Rim",
	"Swag Rim",
	"Step Rim",
	"R&B Rim 4",
	"Street Rim",
	"Regular Rim",
	"TR909 Rim",
	"TR808 Rim",
	"Reg.F.Tom p",
	"Reg.F.Tom f",
	"Reg.L.Tom p",
	"Reg.L.Tom f",
	"Reg.M.Tom p",
	"Reg.M.Tom f",
	"Reg.H.Tom p",
	"Reg.H.Tom f",
	"Reg.L.TomFlm",
	"Reg.M.TomFlm",
	"Reg.H.TomFlm",
	"Jazz Lo Tom",
	"Jazz Mid Tom",
	"Jazz Hi Tom",
	"Jazz Lo Flm",
	"Jazz Mid Flm",
	"Jazz Hi Flm",
	"Sharp Lo Tom",
	"Sharp Hi Tom",
	"Dry Lo Tom",
	"Dry Hi Tom",
	"TR909 Tom",
	"TR909 DstTom",
	"TR808 Tom",
	"TR606 Tom",
	"Deep Tom",
	"Reg.CHH 1 p",
	"Reg.CHH 1 mf",
	"Reg.CHH 1 f",
	"Reg.CHH 1 ff",
	"Reg.CHH 2 mf",
	"Reg.CHH 2 f",
	"Reg.CHH 2 ff",
	"Reg.PHH mf",
	"Reg.PHH f",
	"Reg.OHH mf",
	"Reg.OHH f",
	"Reg.OHH ff",
	"Rock CHH1 mf",
	"Rock CHH1 f",
	"Rock CHH2 mf",
	"Rock CHH2 f",
	"Rock PHH",
	"Rock OHH",
	"Lo-Bit CHH 1",
	"Lo-Bit CHH 2",
	"Lo-Bit CHH 3",
	"Lo-Bit CHH 4",
	"Lo-Bit CHH 5",
	"Modern CHH",
	"HipHop CHH 1",
	"Urban CHH",
	"Bang CHH",
	"LowDwn CHH",
	"Disc CHH",
	"Club CHH 1",
	"HipHop CHH 2",
	"TR909 CHH 1",
	"TR909 CHH 2",
	"Shaky CHH",
	"Club CHH 2",
	"TR808 CHH 1",
	"TR808 CHH 2",
	"TR606 CHH 1",
	"TR606 CHH 2",
	"TR606 DstCHH",
	"Lite CHH",
	"CR78 CHH",
	"DR55 CHH",
	"Neck CHH",
	"Dance CHH",
	"Street PHH",
	"Swallow PHH",
	"Hip PHH",
	"TR909 PHH 1",
	"TR909 PHH 2",
	"TR808 PHH",
	"TR606 PHH 1",
	"TR606 PHH 2",
	"Lo-Bit PHH",
	"Lo-Bit OHH 1",
	"Lo-Bit OHH 2",
	"Lo-Bit OHH 3",
	"Neck OHH",
	"Bang OHH",
	"HipHop OHH",
	"TR909 OHH 1",
	"TR909 OHH 2",
	"TR808 OHH 1",
	"TR808 OHH 2",
	"TR606 OHH",
	"Lite OHH",
	"CR78 OHH",
	"Crash Cym1 p",
	"Crash Cym1 f",
	"Crash Cym 2",
	"Rock Crash 1",
	"Rock Crash 2",
	"Splash Cym",
	"Jazz Crash",
	"TR909 Crash",
	"TR606 Cym",
	"Ride Cymbal",
	"Ride Bell",
	"Rock Rd Cup",
	"Rock Rd Edge",
	"Jazz Ride p",
	"Jazz Ride mf",
	"TR909 Ride",
	"TR707 Ride",
	"China Cymbal",
	"Concert Cym",
	"Hand Clap",
	"Club Clap",
	"Short Clap",
	"Real Clap",
	"Bright Clap",
	"R8 Clap",
	"Gospel Clap",
	"Amb Clap",
	"Hip Clap",
	"Funk Clap",
	"Group Clap",
	"Claptail",
	"Planet Clap",
	"Royal Clap",
	"Happy Clap",
	"TR808 Clap 1",
	"Disc Clap",
	"Dist Clap",
	"Old Clap",
	"TR909 Clap 1",
	"TR909 Clap 2",
	"TR808 Clap 2",
	"TR707 Clap",
	"Cheap Clap",
	"Finger Snap",
	"Club FinSnap",
	"Single Snap",
	"Snap",
	"Group Snap",
	"Vox Kick 1",
	"Vox Kick 2",
	"VoxKickSweep",
	"Vox Snare 1",
	"Vox Snare 2",
	"Vox Hihat 1",
	"Vox Hihat 2",
	"Vox Hihat 3",
	"Vox Cymbal",
	"Pa!",
	"Chiki!",
	"Cowbell",
	"Cowbell Mute",
	"Wood Block",
	"Claves",
	"TR808 Claves",
	"CR78 Beat",
	"Castanet",
	"Whistle",
	"Bongo Hi Mt",
	"Bongo Hi Slp",
	"Bongo Lo Slp",
	"Bongo Hi Op",
	"Bongo Lo Op",
	"Conga Hi Mt",
	"Conga Lo Mt",
	"Conga Hi Slp",
	"Conga Lo Slp",
	"Conga Hi Op",
	"Conga Lo Op",
	"Conga Slp Op",
	"Conga Efx",
	"Conga Thumb",
	"Timbale 1",
	"Timbale 2",
	"Cabasa Up",
	"Cabasa Down",
	"Cabasa Cut",
	"Maracas",
	"808 Maracas",
	"R8 Shaker 1",
	"R8 Shaker 2",
	"Shaker 1",
	"Shaker 2",
	"Bone Shake",
	"CR78 Guiro",
	"Guiro 1",
	"Guiro 2",
	"Guiro Long",
	"TR727Quijada",
	"Vibraslap",
	"Tamborine 1",
	"Tamborine 2",
	"Tamborine 3",
	"CR78 Tamb",
	"TablaBayam 1",
	"TablaBayam 2",
	"TablaBayam 3",
	"TablaBayam 4",
	"TablaBayam 5",
	"TablaBayam 6",
	"TablaBayam 7",
	"Cajon 1",
	"Cajon 2",
	"Cajon 3",
	"Udo",
	"Udu Pot Hi",
	"Udu Pot Slp",
	"SprgDrm Hit",
	"Op Pandeiro",
	"Mt Pandeiro",
	"Cuica",
	"Timpani p",
	"Timpani f",
	"Timpani Roll",
	"Timpani Lp",
	"ConcertBD p",
	"ConcertBD f",
	"ConcertBD ff",
	"ConcertBD Lp",
	"Triangle 1",
	"Triangle 2",
	"Tibet Cymbal",
	"Slight Bell",
	"Wind Chime",
	"Crotale",
	"R8 Click",
	"Metro Bell",
	"Metro Click",
	"MC500 Beep 1",
	"MC500 Beep 2",
	"DR202 Beep",
	"Low Saw1",
	"Low Saw1 inv",
	"Low Saw2",
	"Low Pulse 1",
	"Low Pulse 2",
	"Low Square",
	"Low Sine",
	"Low Triangle",
	"Low White Nz",
	"Low Pink Nz",
	"DC",
	"Reverse Cym",
};

